import { images } from "./images";

export const projectCategories = [
  { id: "all", label: "All Projects" },
  { id: "frontend", label: "Frontend" },
  { id: "backend", label: "Backend" },
  { id: "fullstack", label: "" },
];

export const projects = [
  {
    id: "1",
    title: "Sunnah Store",
    description: "Online Store for halal businesses",
    category: "web",
    stack: "MERN Stack",
    image: images.projects.halalJibika,
    technologies: ["Next.js", "Tailwind", "AuthJs"],
    liveUrl: "https://e-coomerce-project.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/e-coomerce-project",
  },
  {
    id: "2",
    title: "Institutional Website",
    description: "Information and services for students",
    category: "web",
    stack: "MERN Stack",
    image: images.projects.eLearning,
    technologies: ["React", "Bootstrap"],
    liveUrl: "https://bou-university-design.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/bou-university-design",
  },
  {
    id: "3",
    title: "Smart Invoice generator",
    description: "Generate professional invoices easily",
    category: "web",
    stack: "MERN Stack",
    image: "https://i.postimg.cc/yNHvr4M7/invoice.png",
    technologies: ["React.js", "Tailwind CSS"],
    liveUrl: "https://smart-invoice-generator-tau.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/smart-invoice-generator",
  },
  {
    id: "4",
    title: "Task Management Todo app",
    description: "Application  for managing tasks and projects",
    category: "web",
    stack: "MERN Stack",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToOdMXwSSkScnMIPwA6y1MOeNcL9-3tTbj9ac6mlTTae-6xdClLJiMsdtWCNe7dNlhvZg&usqp=CAU",
    technologies: ["React", "Tailwind CSS"],
    category: "frontend",
    liveUrl: "https://task-management-jet.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/Task-management",
  },
  {
    id: "5",
    title: "Personal Website",
    description: "personal portfolio website",
    category: "web",
    stack: "MERN Stack",
    image:
      "https://market-resized.envatousercontent.com/previews/files/602725017/preview_01.jpg?w=590&h=300&cf_fit=crop&crop=top&format=auto&q=85&s=f39831e1ef4e912898524370d5c44efb1d2bffb4a830e0890331523745f64680",
    technologies: ["React", "Tailwind CSS"],
    category: "frontend",
    liveUrl: "https://mamu-seven.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/mamu",
  },

  {
    id: 6,
    title: "Dua page",
    description: "A dua page where practical muslim can read dua.",
    category: "frontend",
    stack: "MERN Stack",
    image: "https://i.postimg.cc/9Q02RQ8M/duapage.png",

    technology: ["Next js", "Tailwind CSS"],
    liveUrl: "https://assignment-44f2.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/assignment",
  },
  {
    id: 7,
    title: "Roadmap app",
    description: "Modern roadmap-app for knowing user feedback.",
    category: "frontend",
    stack: "MERN Stack",
    image: "https://i.postimg.cc/VLRs0Tz7/roadmap.png",
    technology: ["React", "Tailwind CSS"],
    liveUrl: "https://roadmapapp-front-end.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/roadmapapp-front-end",
  },
  {
    id: 8,
    title: "Bank Website",
    description: "Bank platform focused on Practicing purpuse.",
    category: "web",
    stack: "MERN Stack",
    image: "https://i.ibb.co/JzFRZ9p/bank-website.jpg",
    technologies: ["React.js", "Tailwind CSS"],
    liveUrl: "https://bank-app-pearl.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/Bank-app-",
  },
  {
    id: 9,
    title: "E-commerce Website",
    description: "A modern e-commerce platform for online shopping.",
    category: "web",
    stack: "WordPress",
    image: images.projects.halalJibika,
    technologies: ["Elementor", "WooCommerce", "WordPress"],
    liveUrl: "https://dev-newfresh.pantheonsite.io/",
  },
  {
    id: 10,
    title: "Portfolio Website",
    description: "A personal portfolio to showcase  works.",
    category: "web",
    stack: "WordPress",
    image: "https://i.postimg.cc/85gvpWDZ/rakib.png",
    technologies: ["Elementor", "WordPress"],
    liveUrl: "https://dev-raku-editz.pantheonsite.io/",
  },
  {
    id: 11,
    title: "Blog website",
    description: "A blog website for sharing articles and insights.",
    category: "web",
    stack: "WordPress",
    image: "https://i.postimg.cc/qqrn1Fr6/businessly.png",
    technologies: ["Custom Theme", "PHP", " WordPress"],
    liveUrl: "https://dev-my-custom-theme.pantheonsite.io/",
  },
];
